# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.13.2
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
cname: pytest_cache_assert.kyleking.me
copyright_date: '2021'
development_branch: main
doc_dir: docs
include_adrs: false
install_extras: null
minimum_python: 3.8.4
package_name_py: pytest_cache_assert
project_description: Cache assertion data to simplify regression testing of complex
    serializable data
project_name: pytest_cache_assert
repository_namespace: kyleking
repository_provider: https://github.com
